#!/bin/bash

VENV='gootsmoji'

pyenv install --skip-existing "$(head -n1 .python-version)" || return

python -m pip install --upgrade pip setuptools wheel
pip install -r requirements.txt
python3 -m venv "${VENV}"
. "${VENV}"/bin/activate